ad CPPFLAGS
This is what breaks it:
/tmp/jbazeloutput/external/tf_runtime/include/tfrt/concurrency/async_value.h: In member function ‘const absl::lts_20230125::Status* tsl::AsyncValue::GetErrorIfPresent() const’:
/tmp/jbazeloutput/external/tf_runtime/include/tfrt/concurrency/async_value.h:933:1: error: control reaches end of non-void function [-Werror=return-type]
  933 | }